export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="referrer" content="strict-origin-when-cross-origin" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <script src="https://accounts.google.com/gsi/client" async defer></script>
    </>
  )
}
